feat: emit warning if alarm.wav file were not present

diff --git a/pdshell b/pdshell
--- a/pdshell
+++ b/pdshell
@@ -68,25 +68,23 @@ CYAN="\033[0;34m"
 FIN="\033[0m"
 
 
-while [[ $# -gt 0 ]]
+for ((i=1 ; i <= $# ; i++))
 do
-    case $1 in
+    case ${@:$i:1} in
+        -c|--config)
+            ((i++))
+            CONFIG="${@:$i:1}"
+            break
+            ;;
         -nc|--no-config)
             unset CONFIG
-            shift
-            ;;
-        -c|--config)
-            CONFIG="$2"
-            shift && shift
-            ;;
-        *)
-            shift
+            break
             ;;
     esac
 done
 
 # Read the configuration file
-if [ -r $CONFIG ]
+if [[ -r $CONFIG ]]
 then
     source $CONFIG
 fi
@@ -95,6 +93,12 @@ fi
 while [[ $# -gt 0 ]]
 do
     case $1 in
+        -c|--config)
+            shift && shift
+            ;;
+        -nc|--no-config)
+            shift
+            ;;
         --install)
             sudo cp --force "$NAME" "/usr/local/bin/"
             cp --no-clobber config.conf $CONFIG
@@ -203,6 +207,9 @@ countdown() {
     [ "$2" -eq -1 ] && msg="🍅Time left of break:🍅"
     # date in seconds when countdown will end
     start=$(($(date +%s) + $1)); 
+
+    # check if alarm file exists
+    check_files_exist
 
     while [ "$start" -ge "$(date +%s)" ]
     do
@@ -353,6 +360,14 @@ break_stop() {
         unset SSBC_PID
     fi
     $ESBC &>/dev/null &
+}
+
+check_files_exist() {
+    if ! [[ -f $ALARM ]]
+    then
+        echo -e "\n${RED}Warning! ${FIN}\"${YELLOW}${ALARM}${FIN}\" file not found!"
+        echo -e "Did you ran '$ ${YELLOW}./pdshell --install${FIN}'?\n"
+    fi
 }
 
 main() {
